# Importação de Bibliotecas

In [ ]:
import sqlalchemy
import pandas as pd
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin

# Amostragem

In [2]:
database = sqlalchemy.create_engine("sqlite:///../../data/feature_store.db")


with open("abt.sql", "r") as f:
    query = f.read()

df = pd.read_sql(query, database)

In [3]:
df.head()

,DtRef,IdStore,QtdSales7d,QtdSales14d,QtdSales28d,QtdSales42d,QtdSales56d,QtdSales84d,AvgSales7d,AvgSales14d,...,DaysSchoolHoliday56d,DaysSchoolHoliday84d,DaysSchoolHolidayRate7d,DaysSchoolHolidayRate14d,DaysSchoolHolidayRate28d,DaysSchoolHolidayRate42d,DaysSchoolHolidayRate56d,DaysSchoolHolidayRate84d,MonthsSinceCompetition,Target
0,2013-03-26,1,35178.0,65480.0,130434.0,190894.0,255712.0,371108,5863.000000,5456.666667,...,1,12,0.142857,0.071429,0.035714,0.023810,0.017857,0.142857,54.0,168765.0
1,2013-03-26,2,34387.0,59946.0,118145.0,171940.0,227987.0,330911,5731.166667,4995.500000,...,6,10,0.142857,0.071429,0.035714,0.142857,0.107143,0.119048,64.0,161514.0
2,2013-03-26,3,49165.0,87382.0,170497.0,247326.0,330148.0,479824,8194.166667,7281.833333,...,1,5,0.142857,0.071429,0.035714,0.023810,0.017857,0.059524,75.0,237269.0
3,2013-03-26,4,60529.0,111777.0,227692.0,338044.0,458532.0,667726,10088.166667,9314.750000,...,6,10,0.142857,0.071429,0.035714,0.023810,0.107143,0.119048,42.0,321894.0
4,2013-03-26,5,30620.0,53256.0,105674.0,154992.0,206796.0,304004,5103.333333,4438.000000,...,10,12,0.000000,0.000000,0.000000,0.095238,0.178571,0.142857,-25.0,147260.0

In [4]:
df_sorted = df.sort_values('DtRef').reset_index(drop=True)

n = len(df_sorted)
n_train = int(0.6 * n)
n_val   = int(0.2 * n)
n_test  = n - n_train - n_val

train_df = df_sorted.iloc[:n_train]
val_df   = df_sorted.iloc[n_train:n_train + n_val]
test_df  = df_sorted.iloc[n_train + n_val:]

drop_cols = ['Target', 'IdStore', 'DtRef']

X_train = train_df.drop(columns=drop_cols, errors='ignore')
y_train = train_df['Target']

X_val = val_df.drop(columns=drop_cols, errors='ignore')
y_val = val_df['Target']

X_test = test_df.drop(columns=drop_cols, errors='ignore')
y_test = test_df['Target']

# Exploração

## Estatisticas

In [5]:
X_train_numeric = X_train.select_dtypes(include='number')

correlations = X_train_numeric.corrwith(y_train, method='pearson')

top10_positive = correlations.nlargest(10)

top10_negative = correlations.nsmallest(10)

c:\Users\patry\AppData\Local\miniconda3\envs\ds_env\lib\site-packages\numpy\lib\_function_base_impl.py:3045: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
c:\Users\patry\AppData\Local\miniconda3\envs\ds_env\lib\site-packages\numpy\lib\_function_base_impl.py:3046: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

In [6]:
top10_positive.head(10)

QtdSales84d           0.952284
QtdSales56d           0.949342
QtdSales42d           0.946698
QtdSales28d           0.942001
AvgSales84d           0.940410
AvgSales56d           0.935854
AvgSales42d           0.932304
AvgSalesNoPromo84d    0.930760
QtdSales14d           0.929409
AvgSalesNoPromo56d    0.928421
dtype: float64

In [7]:
top10_negative.head(10)

LiftSalesPromo56d   -0.198943
LiftSalesPromo84d   -0.197200
LiftSalesPromo42d   -0.192446
DaysClosed84d       -0.184697
LiftSalesPromo28d   -0.182942
DaysClosed56d       -0.170750
LiftSalesPromo14d   -0.166455
DaysClosed42d       -0.159019
DaysClosed28d       -0.150568
LiftSalesPromo7d    -0.148684
dtype: float64

In [8]:
with pd.option_context('display.max_columns', None, 'display.width', 1000, 'display.max_rows', None):
    display(X_train_numeric.describe().T)

                                   count           mean            std          min            25%            50%            75%           max
QtdSales7d                      533047.0   39838.581855   16111.182947     0.000000   29175.000000   36998.000000   46789.000000  1.931100e+05
QtdSales14d                     534307.0   79621.540947   30168.442738     0.000000   59891.000000   74630.000000   92548.000000  3.599820e+05
QtdSales28d                     534996.0  159155.401816   59186.755058     0.000000  120263.000000  149657.000000  184466.000000  6.892920e+05
QtdSales42d                     534996.0  238783.969065   88071.613250     0.000000  180879.000000  224741.000000  276472.000000  9.772930e+05
QtdSales56d                     534996.0  318307.698693  116907.403940     0.000000  241470.000000  299907.500000  368256.000000  1.284628e+06
QtdSales84d                     534996.0  476953.962385  174567.280092     0.000000  362422.000000  449824.000000  551549.000000  1.864543e+06
AvgSales7d                      532354.0    6915.907215    2692.256248     0.000000    5097.833333    6433.333333    8110.482143  3.236800e+04
AvgSales14d                     533857.0    6918.490009    2539.000316     0.000000    5218.545455    6485.300000    8020.833333  2.845500e+04
AvgSales28d                     534710.0    6901.123667    2487.417376     0.000000    5231.052083    6496.133399    7992.000000  2.609965e+04
AvgSales42d                     534743.0    6890.353137    2464.923319  1426.000000    5236.264706    6494.027778    7975.986111  2.603736e+04
AvgSales56d                     534757.0    6877.330778    2450.040017  1422.454545    5235.511111    6486.704545    7954.488889  2.570776e+04
AvgSales84d                     534774.0    6855.059392    2433.329381  1467.969697    5222.589286    6475.392835    7922.269022  2.535388e+04
MinSales7d                      532354.0    5051.447219    2303.155626     0.000000    3519.000000    4687.000000    6076.000000  3.236800e+04
MinSales14d                     533857.0    4622.440862    2059.390800     0.000000    3268.000000    4321.000000    5519.000000  2.845500e+04
MinSales28d                     534710.0    4337.608229    1930.577649     0.000000    3075.000000    4065.000000    5180.000000  2.467200e+04
MinSales42d                     534743.0    4183.721378    1873.413265     0.000000    2958.000000    3926.000000    5011.000000  2.467200e+04
MinSales56d                     534757.0    4064.917183    1841.186670     0.000000    2859.000000    3824.000000    4874.000000  2.467200e+04
MinSales84d                     534774.0    3888.773355    1796.027364     0.000000    2721.000000    3667.000000    4695.000000  2.467200e+04
MaxSales7d                      532354.0    9010.397102    3611.644371     0.000000    6508.000000    8365.000000   10692.000000  3.803700e+04
MaxSales14d                     533857.0   10232.327245    3745.905115     0.000000    7672.000000    9605.000000   11981.000000  3.803700e+04
MaxSales28d                     534710.0   10876.568192    3951.559886     0.000000    8176.000000   10214.000000   12720.000000  3.803700e+04
MaxSales42d                     534743.0   11224.744315    4084.950739  2009.000000    8436.000000   10531.000000   13140.000000  3.803700e+04
MaxSales56d                     534757.0   11508.096350    4190.597123  2153.000000    8640.000000   10797.000000   13465.000000  3.803700e+04
MaxSales84d                     534774.0   11947.874831    4358.769609  2153.000000    8939.000000   11187.000000   14035.000000  3.803700e+04
QtdSalesPromo7d                 418742.0   26195.768430   15676.638240     0.000000   14128.000000   24101.500000   35129.000000  1.638680e+05
QtdSalesPromo14d                530962.0   41586.942823   17151.072103     0.000000   30609.000000   38456.000000   48580.000000  2.922780e+05
QtdSalesPromo28d                534996.0   82595.146403   31138.607109     0.000000   61941.000000   77473.500000   96768.000000  4.348800e+05
QtdSalesPromo42d                534996.0  123922.247490   44954.071925     0.000000   93812.000000  116666.000000  144854.000000  5.765410e+05
QtdSalesPromo56d                534996.0  165125.569498   58796.246094     0.000000  125709.000000  155682.000000  192463.000000  7.174020e+05
QtdSalesPromo84d                534996.0  246977.738443   86615.586037     0.000000  189071.000000  233420.000000  286846.000000  1.088959e+06
AvgSalesPromo7d                 415581.0    8322.532283    3110.244953     0.000000    6214.000000    7766.200000    9737.500000  3.803700e+04
AvgSalesPromo14d                530081.0    8260.640173    2973.028931     0.000000    6253.800000    7755.400000    9607.250000  3.277360e+04
AvgSalesPromo28d                534672.0    8248.679284    2912.478678     0.000000    6283.500000    7767.600000    9571.700000  3.277360e+04
AvgSalesPromo42d                534743.0    8222.305576    2865.019333  1465.333333    6286.244444    7765.533333    9539.600000  3.087130e+04
AvgSalesPromo56d                534757.0    8201.959703    2834.658555  1526.461538    6284.550000    7758.333333    9511.900000  2.910475e+04
AvgSalesPromo84d                534774.0    8175.279767    2805.446549  1551.409091    6280.466667    7749.645768    9467.147059  2.896945e+04
MinSalesPromo7d                 415581.0    7516.573698    2954.422088     0.000000    5540.000000    6969.000000    8825.000000  3.803700e+04
MinSalesPromo14d                530081.0    6996.271168    2651.558213     0.000000    5235.000000    6541.000000    8168.000000  3.092400e+04
MinSalesPromo28d                534672.0    6554.653883    2426.092092     0.000000    4956.000000    6178.000000    7630.000000  2.993000e+04
MinSalesPromo42d                534743.0    6312.809114    2316.451935     0.000000    4791.000000    5971.000000    7350.000000  2.592100e+04
MinSalesPromo56d                534757.0    6159.021615    2274.961307     0.000000    4674.000000    5837.000000    7169.000000  2.575800e+04
MinSalesPromo84d                534774.0    5971.061003    2246.908610     0.000000    4532.000000    5678.000000    6985.000000  2.467200e+04
MaxSalesPromo7d                 418742.0    9310.661668    3634.668201     0.000000    6884.000000    8739.000000   11029.000000  3.803700e+04
MaxSalesPromo14d                530962.0   10101.498731    3694.070953     0.000000    7594.000000    9505.000000   11843.000000  3.803700e+04
MaxSalesPromo28d                534996.0   10750.400994    3883.074544     0.000000    8111.000000   10111.000000   12577.000000  3.803700e+04
MaxSalesPromo42d                534996.0   11091.439110    4012.006898     0.000000    8368.000000   10418.000000   12962.000000  3.803700e+04
MaxSalesPromo56d                534996.0   11367.059750    4117.722562     0.000000    8558.000000   10672.000000   13296.000000  3.803700e+04
MaxSalesPromo84d                534996.0   11782.947132    4286.983384     0.000000    8860.000000   11054.000000   13825.000000  3.803700e+04
QtdSalesNoPromo7d               532867.0   19266.661433   13715.710032     0.000000    8250.000000   16967.000000   26779.000000  1.772790e+05
QtdSalesNoPromo14d              534127.0   38307.856266   17307.019156     0.000000   27693.000000   35713.000000   45509.000000  3.269820e+05
QtdSalesNoPromo28d              534996.0   76560.255413   33118.038243     0.000000   55373.000000   70899.000000   90158.000000  5.300320e+05
QtdSalesNoPromo42d              534996.0  114861.721575   48807.931996     0.000000   83547.000000  106351.500000  134642.000000  7.269850e+05
QtdSalesNoPromo56d              534996.0  153182.129195   64421.835026     0.000000  111803.750000  141880.000000  179153.000000  8.966900e+05
QtdSalesNoPromo84d              534996.0  229976.223942   95620.732263     0.000000  168606.750000  213166.000000  268130.250000  1.252444e+06
AvgSalesNoPromo7d               531793.0    5912.458971    2522.164027     0.000000    4262.000000    5464.000000    6980.400000  3.301300e+04
AvgSalesNoPromo14d              533374.0    5891.939139    2337.843963     0.000000    4342.857143    5473.285714    6883.134921  2.689233e+04
AvgSalesNoPromo28d              534690.0    5873.553155    2281.582490     0.000000    4353.178571    5479.422619    6846.384615  2.461611e+04
AvgSalesNoPromo42d              534737.0    5867.554487    2262.891363  1141.000000    4358.428571    5478.047619    6839.809524  2.365945e+04
AvgSalesNoPromo56d              534751.0    5858.025351    2251.336083  1245.900000    4356.285714    5474.640000    6827.962963  2.297325e+04
AvgSalesNoPromo84d              534771.0    5840.330565    2236.951842  1369.729730    4350.987805    5462.628571    6811.926829  2.214927e+04
MinSalesNoPromo7d               531793.0    5133.064582    2415.037379     0.000000    3531.000000    4719.000000    6164.000000  3.094000e+04
MinSalesNoPromo14d              533374.0    4636.751951    2067.725353     0.000000    3277.000000    4328.000000    5532.000000  2.316600e+04
MinSalesNoPromo28d              534690.0    4350.844420    1930.015676     0.000000    3089.000000    4072.000000    5194.000000  1.963700e+04
MinSalesNoPromo42d              534737.0    4199.766205    1870.503313     0.000000    2975.000000    3937.000000    5023.000000  1.732800e+04
MinSalesNoPromo56d              534751.0    4084.675082    1837.388812     0.000000    2881.000000    3838.000000    4887.000000  1.662800e+04
MinSalesNoPromo84d              534771.0    3914.929966    1790.008255     0.000000    2743.000000    3692.000000    4708.000000  1.626900e+04
MaxSalesNoPromo7d               532867.0    6712.916311    3006.818188     0.000000    4797.000000    6159.000000    7938.000000  3.740300e+04
MaxSalesNoPromo14d              534127.0    7361.425521    3143.756891     0.000000    5319.000000    6714.000000    8606.000000  3.740300e+04
MaxSalesNoPromo28d              534996.0    8012.170487    3403.829296     0.000000    5758.000000    7299.000000    9396.000000  3.740300e+04
MaxSalesNoPromo42d              534996.0    8435.503288    3592.394412     0.000000    6033.000000    7671.000000    9927.000000  3.740300e+04
MaxSalesNoPromo56d              534996.0    8748.005643    3733.126352     0.000000    6235.000000    7920.000000   10307.000000  3.740300e+04
MaxSalesNoPromo84d              534996.0    9248.994140    3949.350559     0.000000    6558.000000    8368.000000   11008.000000  3.740300e+04
Growth_AvgSales_7d_vs_28d       532347.0       0.002243       0.142893    -1.000000      -0.102061      -0.007585       0.101219  4.083184e+00
Growth_AvgSales_14d_vs_28d      533850.0       0.002504       0.065357    -1.000000      -0.033638       0.002886       0.040311  4.083184e+00
Growth_AvgSales_28d_vs_56d      534710.0       0.003725       0.056741    -1.000000      -0.020803       0.003479       0.030917  6.912721e+00
Growth_AvgSales_42d_vs_84d      534743.0       0.005625       0.052157    -0.363095      -0.019995       0.004930       0.032813  1.858393e+00
LiftSalesPromo7d                414999.0       0.492667       0.439515    -1.000000       0.217058       0.406247       0.661556  6.722485e+00
LiftSalesPromo14d               529566.0       0.437715       0.257613    -1.000000       0.268265       0.411563       0.574037  9.276942e+00
LiftSalesPromo28d               534645.0       0.432401       0.220359    -0.445678       0.281131       0.410251       0.559716  4.620184e+00
LiftSalesPromo42d               534737.0       0.428293       0.208987    -0.330642       0.284542       0.407994       0.549776  5.454580e+00
LiftSalesPromo56d               534751.0       0.426696       0.202220    -0.384205       0.287208       0.408093       0.545254  2.608952e+00
LiftSalesPromo84d               534771.0       0.425865       0.196074    -0.218842       0.291604       0.408161       0.541305  2.331013e+00
SalesGrowth42dYearAgo           218950.0       0.071441       0.165816    -0.751794      -0.009989       0.044016       0.117802  8.767929e+00
SalesPerCustomer7d              532314.0       9.472608       2.050215     0.000000       7.944422       9.267296      10.846830  2.706002e+01
SalesPerCustomer14d             533838.0       9.512537       1.998268     0.000000       7.992607       9.331077      10.873964  2.598292e+01
SalesPerCustomer28d             534703.0       9.511581       1.985485     3.218622       7.992540       9.333703      10.871584  2.186199e+01
SalesPerCustomer42d             534743.0       9.509308       1.980232     3.251039       7.991121       9.329110      10.866520  2.051596e+01
SalesPerCustomer56d             534757.0       9.505031       1.975505     3.281054       7.992021       9.324620      10.861528  2.019531e+01
SalesPerCustomer84d             534774.0       9.497935       1.969550     3.301483       7.989496       9.313126      10.854066  1.910600e+01
AvgSalesPerCustomer7d           532314.0       9.422799       2.033506     0.000000       7.908332       9.215686      10.779481  2.662588e+01
AvgSalesPerCustomer14d          533838.0       9.429613       1.977968     0.000000       7.925133       9.242113      10.766945  2.594476e+01
AvgSalesPerCustomer28d          534703.0       9.423743       1.964624     3.243775       7.920367       9.238526      10.757094  2.195415e+01
AvgSalesPerCustomer42d          534743.0       9.419806       1.959328     3.268002       7.918902       9.233145      10.751130  2.061152e+01
AvgSalesPerCustomer56d          534757.0       9.414236       1.954677     3.302010       7.917833       9.225589      10.746583  2.001191e+01
AvgSalesPerCustomer84d          534774.0       9.405464       1.948749     3.277763       7.915061       9.213824      10.735071  1.896680e+01
QtdCustomers7d                  533047.0    4412.467118    2340.276450     0.000000    3066.000000    3894.000000    5068.000000  3.018800e+04
QtdCustomers14d                 534307.0    8815.892547    4599.397126     0.000000    6180.000000    7805.000000   10098.000000  5.770400e+04
QtdCustomers28d                 534996.0   17626.178257    9121.782365     0.000000   12376.000000   15624.000000   20157.000000  1.097600e+05
QtdCustomers42d                 534996.0   26451.985815   13630.037245     0.000000   18582.000000   23459.000000   30225.000000  1.591340e+05
QtdCustomers56d                 534996.0   35276.103141   18128.164303     0.000000   24789.000000   31304.000000   40302.000000  2.120450e+05
QtdCustomers84d                 534996.0   52892.732219   27096.155013     0.000000   37202.000000   46987.000000   60456.000000  3.090090e+05
AvgCustomers7d                  532354.0     762.316223     371.208775     0.000000     537.000000     677.666667     877.666667  4.392500e+03
AvgCustomers14d                 533857.0     762.000836     365.613020     0.000000     540.222222     678.833333     874.000000  4.121714e+03
AvgCustomers28d                 534710.0     760.664706     362.921558     0.000000     540.347826     678.958333     872.500000  3.937083e+03
AvgCustomers42d                 534743.0     759.874068     361.661581   217.777778     540.277778     678.939394     872.000000  3.858829e+03
AvgCustomers56d                 534757.0     758.914319     360.730628   219.708333     539.844444     678.395833     871.191489  3.818978e+03
AvgCustomers84d                 534774.0     757.150313     359.421735   223.222222     538.730456     677.181187     870.820896  3.756681e+03
MinCustomers7d                  532354.0     585.149564     327.054516     0.000000     387.000000     511.000000     691.000000  4.033000e+03
MinCustomers14d                 533857.0     548.105611     307.367880     0.000000     363.000000     480.000000     644.000000  3.499000e+03
MinCustomers28d                 534710.0     520.334492     292.811050     0.000000     346.000000     455.000000     611.000000  3.292000e+03
MinCustomers42d                 534743.0     504.290386     284.799319     0.000000     334.000000     443.000000     592.000000  3.183000e+03
MinCustomers56d                 534757.0     490.998143     278.952985     0.000000     324.000000     432.000000     577.000000  3.079000e+03
MinCustomers84d                 534774.0     470.276087     269.700678     0.000000     309.000000     414.000000     555.000000  3.041000e+03
MaxCustomers7d                  533047.0     927.620932     446.451609     0.000000     651.000000     829.000000    1076.000000  5.387000e+03
MaxCustomers14d                 534307.0    1005.703461     463.230241     0.000000     713.000000     908.000000    1166.000000  5.387000e+03
MaxCustomers28d                 534996.0    1056.711732     482.787731     0.000000     749.000000     954.000000    1231.000000  5.387000e+03
MaxCustomers42d                 534996.0    1086.538628     494.875000     0.000000     773.000000     981.000000    1266.000000  5.387000e+03
MaxCustomers56d                 534996.0    1110.874278     503.810901     0.000000     790.000000    1003.000000    1293.000000  5.387000e+03
MaxCustomers84d                 534996.0    1149.597561     518.426818     0.000000     818.000000    1038.000000    1335.000000  7.388000e+03
QtdCustomersPromo7d             418742.0    2711.412383    1857.030399     0.000000    1399.000000    2394.000000    3548.000000  2.163000e+04
QtdCustomersPromo14d            530962.0    4304.978253    2230.079666     0.000000    2963.250000    3803.000000    4998.000000  4.231200e+04
QtdCustomersPromo28d            534996.0    8553.466843    4200.944942     0.000000    5975.000000    7638.000000    9954.250000  6.394200e+04
QtdCustomersPromo42d            534996.0   12838.435424    6158.564167     0.000000    9038.000000   11502.000000   14879.000000  8.469000e+04
QtdCustomersPromo56d            534996.0   17114.607184    8115.885181     0.000000   12104.000000   15354.000000   19802.000000  1.050480e+05
QtdCustomersPromo84d            534996.0   25611.935534   12019.822089     0.000000   18190.000000   23053.000000   29624.000000  1.526130e+05
AvgCustomersPromo7d             415581.0     857.426605     399.355549     0.000000     609.000000     770.000000     992.500000  5.069000e+03
AvgCustomersPromo14d            530081.0     852.210186     393.449592     0.000000     607.000000     766.000000     983.800000  4.463000e+03
AvgCustomersPromo28d            534672.0     851.237408     390.317611     0.000000     608.444444     765.555556     984.083333  4.298923e+03
AvgCustomersPromo42d            534743.0     849.389340     388.107356   232.750000     608.357143     764.733333     981.266667  4.279944e+03
AvgCustomersPromo56d            534757.0     848.012466     386.634183   244.083333     607.894737     763.750000     979.947368  4.234652e+03
AvgCustomersPromo84d            534774.0     846.124766     384.966261   247.500000     607.363636     763.666667     978.391417  4.155853e+03
MinCustomersPromo7d             415581.0     792.700333     383.268030     0.000000     556.000000     709.000000     920.000000  5.069000e+03
MinCustomersPromo14d            530081.0     751.184340     363.087012     0.000000     530.000000     673.000000     868.000000  4.463000e+03
MinCustomersPromo28d            534672.0     712.924400     344.284908     0.000000     506.000000     640.000000     827.000000  4.033000e+03
MinCustomersPromo42d            534743.0     691.162029     334.677706     0.000000     491.000000     621.000000     801.000000  3.905000e+03
MinCustomersPromo56d            534757.0     676.686121     329.755262     0.000000     481.000000     609.000000     786.000000  3.840000e+03
MinCustomersPromo84d            534774.0     657.589112     323.971357     0.000000     467.000000     595.000000     767.000000  3.627000e+03
MaxCustomersPromo7d             418742.0     929.303437     434.419301     0.000000     662.000000     841.000000    1086.000000  5.106000e+03

In [9]:
# Tabela de frequência relativa das variáveis categóricas StoreType e Assortment
print("Frequência relativa de StoreType:")
print(X_train['StoreType'].value_counts(normalize=True, dropna=False))
print("\nFrequência relativa de Assortment:")
print(X_train['Assortment'].value_counts(normalize=True, dropna=False))

Frequência relativa de StoreType:
StoreType
a    0.539903
d    0.312109
c    0.132743
b    0.015245
Name: proportion, dtype: float64

Frequência relativa de Assortment:
Assortment
a    0.531873
c    0.460056
b    0.008071
Name: proportion, dtype: float64

## Tipos

In [10]:
# Mostrar as colunas cujas variáveis são do tipo object
object_cols = X_train.select_dtypes(include='object').columns.tolist()
print("Colunas do tipo object:", object_cols)

Colunas do tipo object: ['StoreType', 'Assortment']

In [13]:
X_train['SalesGrowth42dYearAgo'] = pd.to_numeric(X_train['SalesGrowth42dYearAgo'], errors='coerce')
print("Tipo após conversão:", X_train['SalesGrowth42dYearAgo'].dtype)
print("Valores NaN após conversão:", X_train['SalesGrowth42dYearAgo'].isna().sum())

Tipo após conversão: float64
Valores NaN após conversão: 316046

## NaN

In [ ]:
nan_pct = X_train.isna().mean() * 100

nan_pct = nan_pct[nan_pct > 0].sort_values(ascending=False)

nan_pct_df = nan_pct.to_frame('Porcentagem_NaN').reset_index().rename(columns={'index': 'Coluna'})

with pd.option_context('display.max_columns', None, 'display.width', 1000, 'display.max_rows', None):
    display(nan_pct_df)

                             Coluna  Porcentagem_NaN
0             SalesGrowth42dYearAgo        59.074460
1                   CompetitionOpen        31.748649
2            MonthsSinceCompetition        31.748649
3                  LiftSalesPromo7d        22.429513
4               MinCustomersPromo7d        22.320728
5               AvgCustomersPromo7d        22.320728
6                   MinSalesPromo7d        22.320728
7                   AvgSalesPromo7d        22.320728
8                   QtdSalesPromo7d        21.729882
9                   MaxSalesPromo7d        21.729882
10              QtdCustomersPromo7d        21.729882
11              MaxCustomersPromo7d        21.729882
12                LiftSalesPromo14d         1.014961
13             AvgCustomersPromo14d         0.918698
14             MinCustomersPromo14d         0.918698
15                 AvgSalesPromo14d         0.918698
16                 MinSalesPromo14d         0.918698
17                 QtdSalesPromo14d         0.754024
18             QtdCustomersPromo14d         0.754024
19             MaxCustomersPromo14d         0.754024
20                 MaxSalesPromo14d         0.754024
21            MinCustomersNoPromo7d         0.598696
22                MinSalesNoPromo7d         0.598696
23                AvgSalesNoPromo7d         0.598696
24            AvgCustomersNoPromo7d         0.598696
25               SalesPerCustomer7d         0.501312
26            AvgSalesPerCustomer7d         0.501312
27    Growth_AvgCustomers_7d_vs_28d         0.495144
28        Growth_AvgSales_7d_vs_28d         0.495144
29                   MinCustomers7d         0.493835
30                   AvgCustomers7d         0.493835
31                       MinSales7d         0.493835
32                       MaxSales7d         0.493835
33                       AvgSales7d         0.493835
34            MaxCustomersNoPromo7d         0.397947
35            QtdCustomersNoPromo7d         0.397947
36                QtdSalesNoPromo7d         0.397947
37                MaxSalesNoPromo7d         0.397947
38                   QtdCustomers7d         0.364302
39                       QtdSales7d         0.364302
40                   MaxCustomers7d         0.364302
41               AvgSalesNoPromo14d         0.303180
42           AvgCustomersNoPromo14d         0.303180
43               MinSalesNoPromo14d         0.303180
44           MinCustomersNoPromo14d         0.303180
45              CompetitionDistance         0.268974
46              SalesPerCustomer14d         0.216450
47           AvgSalesPerCustomer14d         0.216450
48       Growth_AvgSales_14d_vs_28d         0.214207
49   Growth_AvgCustomers_14d_vs_28d         0.214207
50                  AvgCustomers14d         0.212899
51                      MaxSales14d         0.212899
52                      MinSales14d         0.212899
53                      AvgSales14d         0.212899
54                  MinCustomers14d         0.212899
55               MaxSalesNoPromo14d         0.162431
56           QtdCustomersNoPromo14d         0.162431
57           MaxCustomersNoPromo14d         0.162431
58               QtdSalesNoPromo14d         0.162431
59                      QtdSales14d         0.128786
60                  MaxCustomers14d         0.128786
61                  QtdCustomers14d         0.128786
62                LiftSalesPromo28d         0.065608
63             AvgCustomersPromo28d         0.060561
64                 MinSalesPromo28d         0.060561
65                 AvgSalesPromo28d         0.060561
66             MinCustomersPromo28d         0.060561
67           AvgCustomersNoPromo28d         0.057197
68           MinCustomersNoPromo28d         0.057197
69               AvgSalesNoPromo28d         0.057197
70               MinSalesNoPromo28d         0.057197
71              SalesPerCustomer28d         0.054767
72           AvgSalesPerCustomer28d         0.054767
73   Growth_AvgCustomers_28d_vs_56d         0.053458
74                      AvgSales28d         0.053458
75                      MaxSales28d         0.053458
76       Growth_AvgSales_28d_vs_56d         0.053458
77                      MinSales28d         0.053458
78                  MinCustomers28d         0.053458
79                  AvgCustomers28d         0.053458
80           MinCustomersNoPromo42d         0.048412
81           AvgCustomersNoPromo42d         0.048412
82               MinSalesNoPromo42d         0.048412
83                LiftSalesPromo42d         0.048412
84               AvgSalesNoPromo42d         0.048412
85                 AvgSalesPromo42d         0.047290
86       Growth_AvgSales_42d_vs_84d         0.047290
87                      AvgSales42d         0.047290
88                      MinSales42d         0.047290
89                 MinSalesPromo42d         0.047290
90                      MaxSales42d         0.047290
91              SalesPerCustomer42d         0.047290
92   Growth_AvgCustomers_42d_vs_84d         0.047290
93                  AvgCustomers42d         0.047290
94                  MinCustomers42d         0.047290
95             AvgCustomersPromo42d         0.047290
96           AvgSalesPerCustomer42d         0.047290
97             MinCustomersPromo42d         0.047290
98           AvgCustomersNoPromo56d         0.045795
99           MinCustomersNoPromo56d         0.045795
100              MinSalesNoPromo56d         0.045795
101               LiftSalesPromo56d         0.045795
102              AvgSalesNoPromo56d         0.045795
103                 AvgCustomers56d         0.044673
104             SalesPerCustomer56d         0.044673
105            MinCustomersPromo56d         0.044673
106                AvgSalesPromo56d         0.044673
107                     MaxSales56d         0.044673
108                MinSalesPromo56d         0.044673
109                     MinSales56d         0.044673
110                     AvgSales56d         0.044673
111          AvgSalesPerCustomer56d         0.044673
112            AvgCustomersPromo56d         0.044673
113                 MinCustomers56d         0.044673
114          MinCustomersNoPromo84d         0.042056
115          AvgCustomersNoPromo84d         0.042056
116              AvgSalesNoPromo84d         0.042056
117              MinSalesNoPromo84d         0.042056
118               LiftSalesPromo84d         0.042056
119                MinSalesPromo84d         0.041496
120                AvgSalesPromo84d         0.041496
121                     AvgSales84d         0.041496
122                     MinSales84d         0.041496
123                     MaxSales84d         0.041496
124             SalesPerCustomer84d         0.041496
125          AvgSalesPerCustomer84d         0.041496
126                 AvgCustomers84d         0.041496
127                 MinCustomers84d         0.041496
128            AvgCustomersPromo84d         0.041496
129            MinCustomersPromo84d         0.041496

## Tratamento NaN

In [ ]:

class NullImputer(BaseEstimator, TransformerMixin):
    def __init__(self):
        # define columns and fill values for different groups
        self.lift_vars = [
            'LiftSalesPromo7d', 'LiftSalesPromo14d', 'LiftSalesPromo28d', 
            'LiftSalesPromo42d', 'LiftSalesPromo56d', 'LiftSalesPromo84d', 
            'MonthsSinceCompetition'
        ]
        self.cols_promo = [
            'SalesGrowth42dYearAgo_missing', 'QtdSalesPromo7d', 'QtdSalesPromo14d', 
            'QtdSalesPromo28d', 'QtdSalesPromo42d', 'QtdSalesPromo56d', 'QtdSalesPromo84d', 
            'AvgSalesPromo7d', 'AvgSalesPromo14d', 'AvgSalesPromo28d', 'AvgSalesPromo42d', 
            'AvgSalesPromo56d', 'AvgSalesPromo84d', 'MinSalesPromo7d', 'MinSalesPromo14d', 
            'MinSalesPromo28d', 'MinSalesPromo42d', 'MinSalesPromo56d', 'MinSalesPromo84d', 
            'MaxSalesPromo7d', 'MaxSalesPromo14d', 'MaxSalesPromo28d', 'MaxSalesPromo42d', 
            'MaxSalesPromo56d', 'MaxSalesPromo84d', 'QtdSalesNoPromo7d', 'QtdSalesNoPromo14d', 
            'QtdSalesNoPromo28d', 'QtdSalesNoPromo42d', 'QtdSalesNoPromo56d', 'QtdSalesNoPromo84d', 
            'AvgSalesNoPromo7d', 'AvgSalesNoPromo14d', 'AvgSalesNoPromo28d', 'AvgSalesNoPromo42d', 
            'AvgSalesNoPromo56d', 'AvgSalesNoPromo84d', 'MinSalesNoPromo7d', 'MinSalesNoPromo14d', 
            'MinSalesNoPromo28d', 'MinSalesNoPromo42d', 'MinSalesNoPromo56d', 'MinSalesNoPromo84d', 
            'MaxSalesNoPromo7d', 'MaxSalesNoPromo14d', 'MaxSalesNoPromo28d', 'MaxSalesNoPromo42d', 
            'MaxSalesNoPromo56d', 'MaxSalesNoPromo84d', 'QtdCustomersPromo7d', 'QtdCustomersPromo14d', 
            'QtdCustomersPromo28d', 'QtdCustomersPromo42d', 'QtdCustomersPromo56d', 'QtdCustomersPromo84d', 
            'AvgCustomersPromo7d', 'AvgCustomersPromo14d', 'AvgCustomersPromo28d', 'AvgCustomersPromo42d', 
            'AvgCustomersPromo56d', 'AvgCustomersPromo84d', 'MinCustomersPromo7d', 'MinCustomersPromo14d', 
            'MinCustomersPromo28d', 'MinCustomersPromo42d', 'MinCustomersPromo56d', 'MinCustomersPromo84d', 
            'MaxCustomersPromo7d', 'MaxCustomersPromo14d', 'MaxCustomersPromo28d', 'MaxCustomersPromo42d', 
            'MaxCustomersPromo56d', 'MaxCustomersPromo84d', 'QtdCustomersNoPromo7d', 'QtdCustomersNoPromo14d', 
            'QtdCustomersNoPromo28d', 'QtdCustomersNoPromo42d', 'QtdCustomersNoPromo56d', 'QtdCustomersNoPromo84d', 
            'AvgCustomersNoPromo7d', 'AvgCustomersNoPromo14d', 'AvgCustomersNoPromo28d', 'AvgCustomersNoPromo42d', 
            'AvgCustomersNoPromo56d', 'AvgCustomersNoPromo84d', 'MinCustomersNoPromo7d', 'MinCustomersNoPromo14d', 
            'MinCustomersNoPromo28d', 'MinCustomersNoPromo42d', 'MinCustomersNoPromo56d', 'MinCustomersNoPromo84d', 
            'MaxCustomersNoPromo7d', 'MaxCustomersNoPromo14d', 'MaxCustomersNoPromo28d', 'MaxCustomersNoPromo42d', 
            'MaxCustomersNoPromo56d', 'MaxCustomersNoPromo84d', 'Promo2Open', 'DaysPromo7d', 
            'DaysPromo14d', 'DaysPromo28d', 'DaysPromo42d', 'DaysPromo56d', 'DaysPromo84d', 
            'DaysNoPromo7d', 'DaysNoPromo14d', 'DaysNoPromo28d', 'DaysNoPromo42d', 'DaysNoPromo56d', 
            'DaysNoPromo84d', 'DaysPromoRate7d', 'DaysPromoRate14d', 'DaysPromoRate28d', 
            'DaysPromoRate42d', 'DaysPromoRate56d', 'DaysPromoRate84d'
        ]
        self.cols_sales_customers = [
            'QtdSales7d', 'QtdSales14d', 'AvgSales7d', 'AvgSales14d', 'AvgSales28d', 'AvgSales42d', 
            'AvgSales56d', 'AvgSales84d', 'MinSales7d', 'MinSales14d', 'MinSales28d', 'MinSales42d', 
            'MinSales56d', 'MinSales84d', 'MaxSales7d', 'MaxSales14d', 'MaxSales28d', 'MaxSales42d', 
            'MaxSales56d', 'MaxSales84d', 'Growth_AvgSales_7d_vs_28d', 'Growth_AvgSales_14d_vs_28d', 
            'Growth_AvgSales_28d_vs_56d', 'Growth_AvgSales_42d_vs_84d', 'SalesGrowth42dYearAgo', 
            'SalesPerCustomer7d', 'SalesPerCustomer14d', 'SalesPerCustomer28d', 'SalesPerCustomer42d', 
            'SalesPerCustomer56d', 'SalesPerCustomer84d', 'AvgSalesPerCustomer7d', 'AvgSalesPerCustomer14d', 
            'AvgSalesPerCustomer28d', 'AvgSalesPerCustomer42d', 'AvgSalesPerCustomer56d', 'AvgSalesPerCustomer84d', 
            'QtdCustomers7d', 'QtdCustomers14d', 'AvgCustomers7d', 'AvgCustomers14d', 'AvgCustomers28d', 
            'AvgCustomers42d', 'AvgCustomers56d', 'AvgCustomers84d', 'MinCustomers7d', 'MinCustomers14d', 
            'MinCustomers28d', 'MinCustomers42d', 'MinCustomers56d', 'MinCustomers84d', 'MaxCustomers7d', 
            'MaxCustomers14d', 'Growth_AvgCustomers_7d_vs_28d', 'Growth_AvgCustomers_14d_vs_28d', 
            'Growth_AvgCustomers_28d_vs_56d', 'Growth_AvgCustomers_42d_vs_84d'
        ]

    def fit(self, X, y=None):
        # CompetitionDistance median para imputação
        self.competition_distance_median_ = X['CompetitionDistance'].median()
        return self
    
    def transform(self, X):
        X = X.copy()  # para não alterar o original
        
        # SalesGrowth42dYearAgo_missing
        X["SalesGrowth42dYearAgo_missing"] = X["SalesGrowth42dYearAgo"].isna().astype(int)
        
        # CompetitionOpen_missing
        X["CompetitionOpen_missing"] = X["CompetitionOpen"].isna().astype(int)
        
        # CompetitionOpen: lógica dependente da CompetitionDistance
        def comp_open(row):
            if not pd.isna(row["CompetitionDistance"]):
                return 1
            elif pd.isna(row["CompetitionOpen"]):
                return 0
            else:
                return row["CompetitionOpen"]
        X["CompetitionOpen"] = X.apply(comp_open, axis=1)
        
        # CompetitionDistance_missing
        X["CompetitionDistance_missing"] = X["CompetitionDistance"].isna().astype(int)
        
        # CompetitionDistance imputação
        X["CompetitionDistance"] = X["CompetitionDistance"].fillna(self.competition_distance_median_)
        
        # lift_vars - indicar missing e valor -1 para nulos
        for col in self.lift_vars:
            X[f"{col}_missing"] = X[col].isna().astype(int)
            X[col] = X[col].fillna(-1)
        
        # cols_promo - nulo vira 0
        for col in self.cols_promo:
            if col in X.columns:
                X[col] = X[col].fillna(0)
        
        # cols_sales_customers - nulo vira 0
        for col in self.cols_sales_customers:
            if col in X.columns:
                X[col] = X[col].fillna(0)
        
        return X

cleaning_pipeline = NullImputer()
X_train = cleaning_pipeline.fit_transform(X_train)

In [21]:
nan_pct = X_train.isna().mean() * 100

nan_pct = nan_pct[nan_pct > 0].sort_values(ascending=False)

nan_pct_df = nan_pct.to_frame('Porcentagem_NaN').reset_index().rename(columns={'index': 'Coluna'})

# Exibir todas as colunas e linhas necessárias para visualização adequada
with pd.option_context('display.max_columns', None, 'display.width', 1000, 'display.max_rows', None):
    display(nan_pct_df)

Empty DataFrame
Columns: [Coluna, Porcentagem_NaN]
Index: []